In [1]:
import pandas as pd
import numpy as np

### Step 1: Import Data 

The "real_estate_valuation_data_set.csv" file saves the market historical data of real estate valuation of a Chinese city. The variable information is as follows 

| Variable Name | Role | Type | Description | Units | 
|:--|:--|:--|:--|:--|
|No|ID|Integer||||
|X1 transaction date|Feature|Continuous|for example, 2013.250=2013 March, <br>2013.500=2013 June, etc.||
|X2 house age|Feature|Continuous||year|
|X3 distance to the <br>nearest metro station|Feature|Continuous||meter|
|X4 number of <br>convenience stores|Feature|Integer|number of convenience stores in the<br> living circle on foot|integer|
|X5 latitude|Feature|Continuous|geographic coordinate, latitude|degree|
|X6 longitude|Feature|Continuous|geographic coordinate, longitude|degree|
|Y house price of<br> unit area|Target|Continuous|10000 Chinese Yuan per <br>square metre|10000 CNY/<br>square metre|

In [2]:
# Read the data with pandas
real_estate = pd.read_csv("real_estate_valuation_data_set.csv", index_col=0)

In [3]:
# Show the first five rows of the data
real_estate.head()

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
No,,,,,,,
1,2012.917,32.0,84.87882,10,24.98298,121.54024,2.53
2,2012.917,19.5,306.59470,9,24.98034,121.53951,2.81
3,2013.583,13.3,561.98450,5,24.98746,121.54391,3.15
4,2013.500,13.3,561.98450,5,24.98746,121.54391,3.65
5,2012.833,5.0,390.56840,5,24.97937,121.54245,2.87


In [4]:
# Get the number of instances and features
row_num = real_estate.shape[0]
col_num = real_estate.shape[1]

In [5]:
row_num, col_num

(414, 7)

In [6]:
# Get the input variables X with features from X1 to X6.
X = np.array(real_estate.iloc[:,:6].values)

In [7]:
X.shape

(414, 6)

In [8]:
X

array([[2012.917  ,   32.     ,   84.87882,   10.     ,   24.98298,
         121.54024],
       [2012.917  ,   19.5    ,  306.5947 ,    9.     ,   24.98034,
         121.53951],
       [2013.583  ,   13.3    ,  561.9845 ,    5.     ,   24.98746,
         121.54391],
       ...,
       [2013.25   ,   18.8    ,  390.9696 ,    7.     ,   24.97923,
         121.53986],
       [2013.     ,    8.1    ,  104.8101 ,    5.     ,   24.96674,
         121.54067],
       [2013.5    ,    6.5    ,   90.45606,    9.     ,   24.97433,
         121.5431 ]])

In [9]:
# Get the target values y
y = np.array(real_estate.iloc[:,6].values)

In [10]:
y.shape

(414,)

In [11]:
y

array([2.53, 2.81, 3.15, 3.65, 2.87, 2.14, 2.69, 3.11, 1.25, 1.47, 2.76,
       3.87, 2.62, 1.59, 2.29, 3.37, 4.67, 2.49, 2.82, 3.18, 1.95, 3.44,
       1.64, 3.19, 2.59, 1.8 , 3.75, 2.24, 3.13, 3.81, 1.47, 1.67, 2.28,
       3.29, 3.67, 1.82, 1.53, 1.69, 3.18, 3.08, 1.06, 1.21, 2.31, 2.27,
       3.59, 2.55, 2.8 , 4.1 , 0.89, 0.88, 2.95, 1.38, 1.8 , 2.59, 3.45,
       0.91, 2.79, 3.57, 1.51, 2.83, 1.42, 4.21, 1.85, 3.67, 1.69, 2.95,
       3.38, 3.79, 2.41, 2.8 , 3.93, 2.72, 2.42, 1.33, 3.63, 1.97, 2.45,
       1.71, 1.99, 1.77, 2.69, 2.45, 3.21, 1.18, 2.91, 3.39, 1.8 , 1.22,
       3.2 , 1.69, 3.03, 2.88, 1.45, 1.07, 2.73, 3.45, 3.97, 2.31, 3.4 ,
       4.15, 2.55, 2.19, 3.63, 3.05, 2.03, 4.73, 3.14, 1.77, 2.27, 1.89,
       3.44, 2.63, 1.54, 0.51, 3.55, 3.09, 0.81, 0.87, 2.04, 3.97, 2.09,
       3.2 , 2.17, 3.03, 3.83, 3.24, 4.19, 3.67, 4.05, 2.73, 2.5 , 2.05,
       2.5 , 2.63, 2.81, 1.39, 3.12, 3.16, 2.9 , 2.83, 3.43, 1.93, 2.5 ,
       2.67, 1.89, 3.03, 3.48, 2.88, 3.01, 2.65, 3.

We can transform the continuous target variable (house price) into a categorical variable (house price range) according to the following rule.
|price range|category|label|
|:--:|:--:|:--:|
|$y\leq 1.5$|very low|0|
|$1.5<y\leq2.5$|low|1|
|$2.5<y\leq3.5$|high|2|
|$y>3.5$|very high|3|

In [12]:
y_ = np.zeros(row_num, dtype="int")
y_[y<=1.5] = 0
y_[(y>1.5)*(y<=2.5)] = 1
y_[(y>2.5)*(y<=3.5)] = 2
y_[y>3.5] = 3
y_

array([2, 2, 2, 3, 2, 1, 2, 2, 0, 0, 2, 3, 2, 1, 1, 2, 3, 1, 2, 2, 1, 2,
       1, 2, 2, 1, 3, 1, 2, 3, 0, 1, 1, 2, 3, 1, 1, 1, 2, 2, 0, 0, 1, 1,
       3, 2, 2, 3, 0, 0, 2, 0, 1, 2, 2, 0, 2, 3, 1, 2, 0, 3, 1, 3, 1, 2,
       2, 3, 1, 2, 3, 2, 1, 0, 3, 1, 1, 1, 1, 1, 2, 1, 2, 0, 2, 2, 1, 0,
       2, 1, 2, 2, 0, 0, 2, 2, 3, 1, 2, 3, 2, 1, 3, 2, 1, 3, 2, 1, 1, 1,
       2, 2, 1, 0, 3, 2, 0, 0, 1, 3, 1, 2, 1, 2, 3, 2, 3, 3, 3, 2, 1, 1,
       1, 2, 2, 0, 2, 2, 2, 2, 2, 1, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2,
       0, 0, 0, 1, 2, 1, 3, 2, 0, 3, 3, 1, 3, 2, 1, 1, 0, 3, 3, 1, 2, 1,
       0, 2, 1, 2, 0, 3, 1, 0, 0, 0, 1, 0, 2, 0, 2, 2, 2, 2, 1, 1, 1, 2,
       2, 1, 1, 2, 1, 2, 1, 0, 2, 1, 1, 2, 2, 2, 1, 3, 0, 2, 2, 2, 2, 2,
       3, 2, 2, 2, 2, 2, 0, 2, 2, 0, 1, 0, 0, 1, 1, 2, 3, 2, 2, 1, 1, 2,
       1, 2, 0, 2, 2, 1, 0, 0, 1, 0, 3, 1, 2, 0, 1, 2, 3, 1, 1, 1, 3, 1,
       2, 2, 1, 2, 2, 1, 3, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 1, 1, 1, 3,
       3, 1, 2, 2, 1, 3, 1, 2, 2, 0, 1, 1, 0, 2, 1,

### Step 2: Data Preprocessing

The values of features X1-X6 are in different scales. The feature in a large scale would have a huge influence on label prediction. We shall normalize the values of different features into a uniform scale to balance the contributions of different features to label prediction. Here we use the [MinMaxScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html) to scale the feature values into the range of $[0,1]$. Another choice for feature normalization is [StandardScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html).

In [13]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X)
X = scaler.transform(X)

In [14]:
X

array([[0.27292576, 0.73059361, 0.00951267, 1.        , 0.61694135,
        0.71932284],
       [0.27292576, 0.44520548, 0.04380939, 0.9       , 0.5849491 ,
        0.71145137],
       [1.        , 0.30365297, 0.08331505, 0.5       , 0.67123122,
        0.75889584],
       ...,
       [0.63646288, 0.42922374, 0.05686115, 0.7       , 0.57149782,
        0.71522536],
       [0.36353712, 0.18493151, 0.0125958 , 0.5       , 0.42014057,
        0.72395946],
       [0.90938865, 0.14840183, 0.0103754 , 0.9       , 0.51211827,
        0.75016174]])

### Step 3: Train-Test Split

We randomly split the data $X$ and $y$ into training and test sets with the ratio $1:1$.

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y_, test_size=0.5, random_state=0)

### Step 4: House Price Range Classification with Bagging Decision Tree

**Task 1**: Read Scikit-Learn's [BaggingClassifier API](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.BaggingClassifier.html), and [DecisionTreeClassifier's API](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html), achieve the multi-class house price range classification using the [BaggingClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.BaggingClassifier.html) with "n_estimators" set to 100 and "estimator" set to a [DecisionTreeClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html) with "max_depth=3".

In [16]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
# Train the BaggingClassifier with the training data (X_train and y_train)
##: Write your code here
base_tree = DecisionTreeClassifier(max_depth=3, random_state=0)

bagging_model = BaggingClassifier(estimator=base_tree, n_estimators=100, random_state=0)
bagging_model.fit(X_train, y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(max_depth=3, random_state=0),
                  n_estimators=100, random_state=0)

In [17]:
# Predict the labels of test data
##: Write your code here
y_pred_bag = bagging_model.predict(X_test)

In [18]:
# Compare the ground-truth and predicted labels
##: Write your code here
pd.DataFrame({
    "y_test": y_test,
    "y_pred": y_pred_bag
})

,y_test,y_pred
0,2,2
1,0,0
2,2,2
3,0,0
4,2,2
...,...,...
202,1,2
203,1,1
204,1,1
205,2,2


In [19]:
# Compute the accuracy score as an evaluation of the trained BaggingClassifier.
##: Write your code here
acc_bag = bagging_model.score(X_test, y_test)
print("Bagging Accuracy:", acc_bag)

Bagging Accuracy: 0.6714975845410628


### Step 5: House Price Range Classification with Random Forest

Read [Scikit-Learn's RandomForestClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier), achieve the multi-class house price range classification using the [RandomForestClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier) with "n_estimators" set to 100 and "max_depth" set to 3. Compare its accuracy with the [BaggingClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.BaggingClassifier.html).

In [20]:
from sklearn.ensemble import RandomForestClassifier
# Train the RandomForestClassifier using the training data (X_train and y_train)
##: Write your code here
rf_model = RandomForestClassifier(n_estimators=100, max_depth=3, random_state=0)
rf_model.fit(X_train, y_train)

RandomForestClassifier(max_depth=3, random_state=0)

In [21]:
# Predict the class labels of test data
##: Write your code here
y_pred_rf = rf_model.predict(X_test)

In [22]:
# Compare the ground-truth and predicted class labels
##: Write your code here
pd.DataFrame({
    "Ground Truth": y_test,
    "Predicted": y_pred_rf
})

,Ground Truth,Predicted
0,2,2
1,0,0
2,2,2
3,0,0
4,2,2
...,...,...
202,1,1
203,1,1
204,1,1
205,2,2


In [23]:
# Compute the accuracy score as an evaluation of the trained RandomForestClassifier.
##: Write your code here
acc_rf = rf_model.score(X_test, y_test)
print("Random Forest Accuracy:", acc_rf)

Random Forest Accuracy: 0.6763285024154589


**Futher Exploration (Optional)**:
+ Remove the step of feature normalization (**Step 2**), and evaluate the performance change of the [BaggingClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.BaggingClassifier.html) and [RandomForestClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier).
+ Read Scikit-Learn's [BaggingRegressor API](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.BaggingRegressor.html), and [DecisionTreeRegressor API](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeRegressor.html#sklearn.tree.DecisionTreeRegressor), complete the regression task of predicting the house price of test samples using the [BaggingRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.BaggingRegressor.html) with "n_estimators" set to 100 and "estimator" set to a [DecisionTreeRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeRegressor.html#sklearn.tree.DecisionTreeRegressor) with "max_depth=3".
+ Read Scikit-Learn's [RandomForestRegressor's API](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html), complete the regression task of predicting the house price of test samples using the [RandomForestRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html) with "n_estimators" set to 100 and "max_depth" set to 3. Compare its mean squared error and $R^2$ with [BaggingRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.BaggingRegressor.html).

In [24]:
X_raw = real_estate.iloc[:, :6].values
y_raw = y_

X_train_raw, X_test_raw, y_train_raw, y_test_raw = train_test_split(
    X_raw, y_raw, test_size=0.5, random_state=0
)

# Bagging
bag_raw = BaggingClassifier(
    estimator=DecisionTreeClassifier(max_depth=3),
    n_estimators=100,
    random_state=0
)
bag_raw.fit(X_train_raw, y_train_raw)

acc_bag_raw = bag_raw.score(X_test_raw, y_test_raw)

# Random Forest
rf_raw = RandomForestClassifier(
    n_estimators=100,
    max_depth=3,
    random_state=0
)
rf_raw.fit(X_train_raw, y_train_raw)

acc_rf_raw = rf_raw.score(X_test_raw, y_test_raw)

print("Bagging:", acc_bag_raw)
print("Random Forest:", acc_rf_raw)

Bagging: 0.6714975845410628
Random Forest: 0.6763285024154589


In [25]:
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, r2_score

y_reg = real_estate.iloc[:, -1].values

X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(
    X_raw, y_reg, test_size=0.5, random_state=0
)

bag_reg = BaggingRegressor(
    estimator=DecisionTreeRegressor(max_depth=3),
    n_estimators=100,
    random_state=0
)

bag_reg.fit(X_train_r, y_train_r)

y_pred_bag_reg = bag_reg.predict(X_test_r)

mse_bag = mean_squared_error(y_test_r, y_pred_bag_reg)
r2_bag = r2_score(y_test_r, y_pred_bag_reg)

print("BaggingRegressor MSE:", mse_bag)
print("BaggingRegressor R²:", r2_bag)

BaggingRegressor MSE: 0.2638063405475421
BaggingRegressor R²: 0.6448039608960495


In [26]:
from sklearn.ensemble import RandomForestRegressor

rf_reg = RandomForestRegressor(
    n_estimators=100,
    max_depth=3,
    random_state=0
)

rf_reg.fit(X_train_r, y_train_r)

y_pred_rf_reg = rf_reg.predict(X_test_r)

mse_rf = mean_squared_error(y_test_r, y_pred_rf_reg)
r2_rf = r2_score(y_test_r, y_pred_rf_reg)

print("RandomForestRegressor MSE:", mse_rf)
print("RandomForestRegressor R²:", r2_rf)

RandomForestRegressor MSE: 0.2575414200197887
RandomForestRegressor R²: 0.6532392204585771


In [27]:
pd.DataFrame({
    "Model": ["BaggingRegressor", "RandomForestRegressor"],
    "MSE": [mse_bag, mse_rf],
    "R2": [r2_bag, r2_rf]
})

,Model,MSE,R2
0,BaggingRegressor,0.263806,0.644804
1,RandomForestRegressor,0.257541,0.653239
