In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

### Step 1: Import Data 

The "real_estate_valuation_data_set.csv" file saves the market historical data of real estate valuation of a Chinese city. The variable information is as follows 

| Variable Name | Role | Type | Description | Units | 
|:--|:--|:--|:--|:--|
|No|ID|Integer||||
|X1 transaction date|Feature|Continuous|for example, 2013.250=2013 March, <br>2013.500=2013 June, etc.||
|X2 house age|Feature|Continuous||year|
|X3 distance to the <br>nearest metro station|Feature|Continuous||meter|
|X4 number of <br>convenience stores|Feature|Integer|number of convenience stores in the<br> living circle on foot|integer|
|X5 latitude|Feature|Continuous|geographic coordinate, latitude|degree|
|X6 longitude|Feature|Continuous|geographic coordinate, longitude|degree|
|Y house price of<br> unit area|Target|Continuous|10000 Chinese Yuan per <br>square metre|10000 CNY/<br>square metre|

In [2]:
# Read the data with pandas
real_estate = pd.read_csv("real_estate_valuation_data_set.csv", index_col=0)

In [3]:
# Show the first five rows of the data
real_estate.head()

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
No,,,,,,,
1,2012.917,32.0,84.87882,10,24.98298,121.54024,2.53
2,2012.917,19.5,306.59470,9,24.98034,121.53951,2.81
3,2013.583,13.3,561.98450,5,24.98746,121.54391,3.15
4,2013.500,13.3,561.98450,5,24.98746,121.54391,3.65
5,2012.833,5.0,390.56840,5,24.97937,121.54245,2.87


In [4]:
# Get the number of instances and features
row_num = real_estate.shape[0]
col_num = real_estate.shape[1]

In [5]:
row_num, col_num

(414, 7)

In [6]:
# Get the input variables X with features from X1 to X6.
X = np.array(real_estate.iloc[:,:6].values)

In [7]:
X.shape

(414, 6)

In [8]:
X

array([[2012.917  ,   32.     ,   84.87882,   10.     ,   24.98298,
         121.54024],
       [2012.917  ,   19.5    ,  306.5947 ,    9.     ,   24.98034,
         121.53951],
       [2013.583  ,   13.3    ,  561.9845 ,    5.     ,   24.98746,
         121.54391],
       ...,
       [2013.25   ,   18.8    ,  390.9696 ,    7.     ,   24.97923,
         121.53986],
       [2013.     ,    8.1    ,  104.8101 ,    5.     ,   24.96674,
         121.54067],
       [2013.5    ,    6.5    ,   90.45606,    9.     ,   24.97433,
         121.5431 ]])

In [9]:
# Get the target values y
y = np.array(real_estate.iloc[:,6].values)

In [10]:
y.shape

(414,)

In [11]:
y

array([2.53, 2.81, 3.15, 3.65, 2.87, 2.14, 2.69, 3.11, 1.25, 1.47, 2.76,
       3.87, 2.62, 1.59, 2.29, 3.37, 4.67, 2.49, 2.82, 3.18, 1.95, 3.44,
       1.64, 3.19, 2.59, 1.8 , 3.75, 2.24, 3.13, 3.81, 1.47, 1.67, 2.28,
       3.29, 3.67, 1.82, 1.53, 1.69, 3.18, 3.08, 1.06, 1.21, 2.31, 2.27,
       3.59, 2.55, 2.8 , 4.1 , 0.89, 0.88, 2.95, 1.38, 1.8 , 2.59, 3.45,
       0.91, 2.79, 3.57, 1.51, 2.83, 1.42, 4.21, 1.85, 3.67, 1.69, 2.95,
       3.38, 3.79, 2.41, 2.8 , 3.93, 2.72, 2.42, 1.33, 3.63, 1.97, 2.45,
       1.71, 1.99, 1.77, 2.69, 2.45, 3.21, 1.18, 2.91, 3.39, 1.8 , 1.22,
       3.2 , 1.69, 3.03, 2.88, 1.45, 1.07, 2.73, 3.45, 3.97, 2.31, 3.4 ,
       4.15, 2.55, 2.19, 3.63, 3.05, 2.03, 4.73, 3.14, 1.77, 2.27, 1.89,
       3.44, 2.63, 1.54, 0.51, 3.55, 3.09, 0.81, 0.87, 2.04, 3.97, 2.09,
       3.2 , 2.17, 3.03, 3.83, 3.24, 4.19, 3.67, 4.05, 2.73, 2.5 , 2.05,
       2.5 , 2.63, 2.81, 1.39, 3.12, 3.16, 2.9 , 2.83, 3.43, 1.93, 2.5 ,
       2.67, 1.89, 3.03, 3.48, 2.88, 3.01, 2.65, 3.

### Step 2: Data Preprocessing

The values of features X1-X6 are in different scales. The feature in a large scale would have a huge influence on target value prediction. We shall normalize the values of different features into a uniform scale to balance the contributions of different features to target value prediction. Here we use the [MinMaxScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html) to scale the feature values into the range of $[0,1]$. Another choice for feature normalization is [StandardScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html).

In [12]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X)
X = scaler.transform(X)

In [13]:
X

array([[0.27292576, 0.73059361, 0.00951267, 1.        , 0.61694135,
        0.71932284],
       [0.27292576, 0.44520548, 0.04380939, 0.9       , 0.5849491 ,
        0.71145137],
       [1.        , 0.30365297, 0.08331505, 0.5       , 0.67123122,
        0.75889584],
       ...,
       [0.63646288, 0.42922374, 0.05686115, 0.7       , 0.57149782,
        0.71522536],
       [0.36353712, 0.18493151, 0.0125958 , 0.5       , 0.42014057,
        0.72395946],
       [0.90938865, 0.14840183, 0.0103754 , 0.9       , 0.51211827,
        0.75016174]])

### Step 3: Train-Test Split

We randomly split the data $X$ and $y$ into training and test sets with the ratio $1:1$.

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.5, random_state=0)

### Step 4: House Price Prediction with Gaussian Process Regression

Read [Scikit-Learn's GaussianProcessRegressor API](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessRegressor.html), and implement the Gaussian process regression model with RBF kernel $k_{\mathrm{SE}}\left(\mathbf{x}_{i}, \mathbf{x}_{j}\right)=\sigma_f^{2} \exp \left(-\frac{1}{2 \ell^{2}}\left\|\mathbf{x}_{i}-\mathbf{x}_{j}\right\|_2^{2}\right)$, as well as the additive i.i.d Gaussian noise with zero mean and variance $\sigma_n^2$. 

**Task 1**: Implement the Gaussian process regression model with the hyperparameter setting: signal variance $\sigma_f^{2}=1.5$, length-scale $\ell=1.5$ and noise variance $\sigma_n^2=0.01$. Keep the hyperparameters fixed when fitting the model. 

In [15]:
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, ConstantKernel
# Train the Gaussian process regression model with the training data (X_train and y_train)
##: Write your code here
kernel = ConstantKernel(constant_value=1.5) * RBF(length_scale=1.5)

gpr = GaussianProcessRegressor(
    kernel=kernel,
    alpha=0.01,
    optimizer=None,
    random_state=0
)

gpr.fit(X_train, y_train)

GaussianProcessRegressor(alpha=0.01, kernel=1.22**2 * RBF(length_scale=1.5),
                         optimizer=None, random_state=0)

In [16]:
# Predict the target values for the test data
##: Write your code here
y_pred = gpr.predict(X_test)
y_pred

array([2.73576386, 1.24529008, 2.98469622, 1.24269651, 3.2920239 ,
       2.79648627, 2.96097889, 2.56218762, 3.37531305, 3.11460733,
       3.09925669, 2.61161089, 2.65420539, 2.84850587, 3.40339705,
       2.98305523, 2.696414  , 2.94851879, 2.61608829, 2.8939753 ,
       3.46001507, 1.74849652, 2.36608056, 3.1400591 , 3.41524596,
       2.85323413, 2.90677349, 1.47119426, 3.50707603, 1.34214332,
       3.14512487, 2.37019961, 3.14637916, 3.25394375, 2.8143156 ,
       1.87046779, 3.09806743, 2.36580013, 3.32315839, 0.88372403,
       3.86424709, 2.47175158, 1.87417203, 3.15839737, 1.33052203,
       2.97956743, 2.43887602, 1.2469148 , 1.93014381, 3.51235308,
       3.75622112, 2.33580372, 2.88587098, 1.46799088, 1.71426505,
       2.32619729, 3.63982163, 2.65053885, 2.89065728, 2.02484028,
       2.70778452, 3.29952551, 2.78929758, 3.23115186, 2.44574919,
       1.46237651, 1.10889718, 2.24515123, 3.29562613, 2.79648627,
       1.81861802, 3.29032179, 3.17088272, 1.68763481, 2.98849

In [17]:
# Compare the ground-truth and predicted target values
##: Write your code here
pd.DataFrame({
    "Ground Truth": y_test,
    "Predicted": y_pred
})

,Ground Truth,Predicted
0,3.02,2.735764
1,0.96,1.245290
2,3.07,2.984696
3,1.04,1.242697
4,3.35,3.292024
...,...,...
202,2.47,2.618869
203,1.97,1.434335
204,2.24,2.815379
205,3.15,3.298686


Compute the $R^2$ score as an evaluation of the trained GaussianProcessRegressor model. The best possible $R^2$ score is 1.0

In [18]:
##: Write your code here
score = gpr.score(X_test, y_test)
print("R² score:", score)

R² score: 0.7125702112336296


In [19]:
# Print the log marginal likehood value of the fitted model
##: Write your code here
lml_value = gpr.log_marginal_likelihood_value_
print("Log Marginal Likelihood:", lml_value)

Log Marginal Likelihood: -2842.653598822972


**Task 2**: Use [GaussianProcessRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessRegressor.html)'s log marginal likelihood value to select the best hyperparameter setting when signal variance $\sigma_f^2$ varies in the set $\{1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5\}$, length-scale $\ell$ in $\{1, 2, 3, 4, 5\}$ and noise variance $\sigma_n^2$ in $\{0.0001,0.001,0.01,0.1,1\}$. Write a grid search program to do model selection, do not use [GaussianProcessRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessRegressor.html)'s automatic hyperparameter optimizer, report the best hyperparameter setting as well as the corresponding model's prediction performance. 

In [20]:
# Use grid search to find the best hyperparameter setting
##: Write your code here
sigma_f2_values = [1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5]
length_scale_values = [1, 2, 3, 4, 5]
noise_values = [0.0001, 0.001, 0.01, 0.1, 1]

best_lml = -np.inf
best_model = None
best_params = None

# Grid search
for sigma_f2 in sigma_f2_values:
    for length_scale in length_scale_values:
        for noise_var in noise_values:

            kernel = ConstantKernel(constant_value=sigma_f2) * RBF(length_scale=length_scale)

            gpr_best_model = GaussianProcessRegressor(
                kernel=kernel,
                alpha=noise_var,
                optimizer=None
            )

            gpr_best_model.fit(X_train, y_train)

            lml = gpr_best_model.log_marginal_likelihood_value_

            if lml > best_lml:
                best_lml = lml
                best_model = gpr_best_model
                best_params = {
                    "sigma_f2": sigma_f2,
                    "length_scale": length_scale,
                    "noise_variance": noise_var
                }
print("Best hyperparameters:", best_params)
print("Best LML:", best_lml)

Best hyperparameters: {'sigma_f2': 5, 'length_scale': 2, 'noise_variance': 1}
Best LML: -246.58951685219813


In [21]:
# Predict the target values for the test data
##: Write your code here
y_pred_best = gpr_best_model.predict(X_test)
y_pred_best

array([2.51876559, 1.20519127, 2.82866355, 1.19111985, 2.67861475,
       2.78445023, 2.78930048, 2.2533201 , 3.25943683, 3.02176934,
       3.07832452, 2.72955382, 2.48744061, 2.75138417, 3.07997777,
       2.56704981, 2.79150924, 2.55582149, 2.73825214, 2.85880095,
       3.22650816, 2.30382607, 2.63117681, 2.98243833, 3.04093253,
       2.94481919, 3.14315646, 1.83088995, 3.1283741 , 1.95347673,
       2.98997633, 2.43728723, 2.65020516, 2.5942892 , 2.9919163 ,
       2.376986  , 3.14875699, 2.57476281, 3.37930243, 0.85836711,
       3.45758006, 2.22687478, 2.26404407, 3.26139767, 1.36894714,
       2.922783  , 2.81669079, 1.20240228, 2.28771615, 3.18556946,
       3.48827049, 2.60563195, 3.13521698, 1.87966361, 2.27796491,
       2.4105007 , 3.17203848, 2.73269111, 2.91290271, 2.3157586 ,
       2.94345392, 2.94634358, 2.50845775, 3.10932884, 2.52983438,
       2.09575233, 1.01089222, 2.33091474, 2.97789807, 2.78445023,
       2.22598706, 2.99336856, 3.02818579, 2.0778209 , 2.73042

In [22]:
# Compare the ground-truth and predicted target values
##: Write your code here
pd.DataFrame({
    "Ground Truth": y_test,
    "Predicted": y_pred_best
})

,Ground Truth,Predicted
0,3.02,2.518766
1,0.96,1.205191
2,3.07,2.828664
3,1.04,1.191120
4,3.35,2.678615
...,...,...
202,2.47,2.636653
203,1.97,2.111931
204,2.24,2.841110
205,3.15,3.170991


Compute the $R^2$ score as an evaluation of the selected best GaussianProcessRegressor model. The best possible $R^2$ score is 1.0.

In [23]:
##: Write your code here
best_score = best_model.score(X_test, y_test)
print("Prediction Performance (R² score):", best_score)

Prediction Performance (R² score): 0.6189450401776146


In [24]:
# Print the log marginal likehood value of the selected best model
##: Write your code here
best_lml = best_model.log_marginal_likelihood_value_
print("Best Log Marginal Likelihood:", best_lml)

Best Log Marginal Likelihood: -246.58951685219813


In [25]:
# Print the best model's hyperparameter setting
##: Write your code here
print("Best hyperparameters:", best_params)

Best hyperparameters: {'sigma_f2': 5, 'length_scale': 2, 'noise_variance': 1}


**Task 3**: Use [GaussianProcessRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessRegressor.html)'s automatic hyperparameter optimizer to find the best hyperparameter setting when $\sigma_f^2$ and $\ell$ both vary in the range $[1,5]$, while $\sigma_n^2$ is fixed as 0.01. Report the best hyperparameter setting as well as the corresponding model's prediction performance. 

In [26]:
# Train the Gaussian process regression model with the activated hyperparameter optimizer
##: Write your code here
kernel = ConstantKernel(constant_value=1.5, constant_value_bounds=(1, 5)) * RBF(length_scale=1.5, length_scale_bounds=(1, 5))

gpr_opt = GaussianProcessRegressor(
    kernel=kernel,
    alpha=0.01,  
    random_state=0
)

gpr_opt.fit(X_train, y_train)

GaussianProcessRegressor(alpha=0.01, kernel=1.22**2 * RBF(length_scale=1.5),
                         random_state=0)

In [27]:
# Predict the target values for the test data
##: Write your code here
y_pred_opt = gpr_opt.predict(X_test)
y_pred_opt

array([2.64308723, 0.79584055, 2.8858282 , 0.75374471, 3.6687125 ,
       2.86119872, 3.0291644 , 2.66914092, 3.2615364 , 3.09524481,
       2.93706754, 2.54708478, 2.61482735, 2.88958038, 3.54437099,
       3.23111684, 2.55878728, 2.08436815, 2.60193749, 2.90023682,
       3.47333092, 1.6829693 , 1.84048491, 3.25713592, 3.4985541 ,
       2.68484325, 2.64666409, 1.51357311, 3.61853815, 1.54048933,
       3.12764473, 2.20351229, 2.69478755, 3.71453332, 2.55185216,
       1.8061682 , 3.32734235, 2.16235773, 3.32173464, 0.44857143,
       3.91861847, 2.54153146, 1.8891986 , 3.41571433, 1.29795033,
       2.821601  , 2.05555063, 1.21518104, 1.80907819, 3.52539119,
       3.88760257, 2.04594184, 2.63710471, 1.02293274, 1.66522961,
       2.36732922, 3.78859226, 2.54992002, 2.77840165, 1.82931754,
       2.58819486, 3.54779299, 2.96716185, 3.23134679, 2.47610633,
       1.4504833 , 1.22320546, 2.26428598, 3.33434216, 2.86119872,
       1.64445879, 3.44128957, 3.47539377, 1.72380349, 3.05482

In [28]:
# Compare the ground-truth and predicted target values
##: Write your code here
pd.DataFrame({
    "Ground Truth": y_test,
    "Predicted": y_pred_opt
})

,Ground Truth,Predicted
0,3.02,2.643087
1,0.96,0.795841
2,3.07,2.885828
3,1.04,0.753745
4,3.35,3.668712
...,...,...
202,2.47,2.617107
203,1.97,1.567128
204,2.24,2.705011
205,3.15,3.221417


Compute the $R^2$ score as an evaluation of the optimized GaussianProcessRegressor model. The best possible $R^2$ score is 1.0.

In [29]:
##: Write your code here
score_opt = gpr_opt.score(X_test, y_test)
print("Optimized R² score:", score_opt)

Optimized R² score: 0.6743255944317531


In [30]:
# Print the log marginal likelihood value of the optimized model
##: Write your code here
lml = gpr_opt.log_marginal_likelihood_value_
print("Optimized Log Marginal Likelihood:", lml)

Optimized Log Marginal Likelihood: -2272.9773418612376


In [31]:
# Print the optimized hyperparameters
##: Write your code here
print("Optimized hyperparameters:")
print("Signal variance:", gpr_opt.kernel_.k1.constant_value)
print("Length-scale:", gpr_opt.kernel_.k2.length_scale)
print("Noise variance:", 0.01)

Optimized hyperparameters:
Signal variance: 4.999999999999999
Length-scale: 1.0
Noise variance: 0.01


Think about why the optimized models (by grid search and automatic optimizer) perform better or worse than the fixed-hyperparameter model.

**Futher Exploration (Optional)**:
+ Choose [DotProduct](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.kernels.DotProduct.html) as the kernel function, evaluate the model's performance with the default kernel hyperparameter setting, and use grid search and [GaussianProcessRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessRegressor.html)'s hyperparameter optimizer to find the best hyperparameter setting. 

In [32]:
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import DotProduct

kernel = DotProduct()

gpr_dot = GaussianProcessRegressor(
    kernel=kernel,
    alpha=0.01,
    random_state=0
)

# predict
gpr_dot.fit(X_train, y_train)

y_pred_dot = gpr_dot.predict(X_test)

# R²
print("DotProduct (default) R²:", gpr_dot.score(X_test, y_test))

# LML
print("DotProduct LML:", gpr_dot.log_marginal_likelihood_value_)

DotProduct (default) R²: 0.6007156624697338
DotProduct LML: -3908.4956887992726


In [33]:
sigma0_values = [0.1, 0.5, 1, 2, 5]

best_lml = -np.inf
best_model_dot = None
best_params_dot = None

for s in sigma0_values:

    kernel = DotProduct(sigma_0=s)

    model = GaussianProcessRegressor(
        kernel=kernel,
        alpha=0.01,
        optimizer=None
    )

    model.fit(X_train, y_train)

    lml = model.log_marginal_likelihood_value_

    if lml > best_lml:
        best_lml = lml
        best_model_dot = model
        best_params_dot = {"sigma_0": s}
        
print("Best DotProduct params:", best_params_dot)
print("Best DotProduct R²:", best_model_dot.score(X_test, y_test))
print("Best DotProduct LML:", best_lml)

Best DotProduct params: {'sigma_0': 2}
Best DotProduct R²: 0.6007200433321582
Best DotProduct LML: -3908.517721691565


In [34]:
kernel = DotProduct(
    sigma_0=1.0,
    sigma_0_bounds=(0.1, 5)
)

gpr_dot_opt = GaussianProcessRegressor(
    kernel=kernel,
    alpha=0.01,
    random_state=0
)

gpr_dot_opt.fit(X_train, y_train)

print("Optimized DotProduct R²:", gpr_dot_opt.score(X_test, y_test))
print("Optimized DotProduct LML:", gpr_dot_opt.log_marginal_likelihood_value_)
print("Optimized sigma_0:", gpr_dot_opt.kernel_.sigma_0)

Optimized DotProduct R²: 0.6007156643664882
Optimized DotProduct LML: -3908.4956887937783
Optimized sigma_0: 2.3041657760979612
